const products = {
  data: [
    {
      id: "0001",
      image: "https://m.media-amazon.com/images/I/71gsjKxyfjL._AC_UY218_.jpg",
      name: "Apple Watch Series 3 (GPS, 42mm) - Silver Aluminum Case with White Sport Band",
      slug: "apple Watch Series 3",
      price: "250",
      brand: "Apple",
      quantity: 11,
      rating: 4.5,
      numReviews: 12,
      description:
        "Low and high heart rate notifications. Emergency SOS. New Breathe watch faces. Automatic workout detection. New yoga and hiking workouts. Advanced features for runners like cadence and pace alerts. New head-to-head competitions. Activity sharing with friends. Personalized coaching. Monthly challenges and achievement awards. You can use Walkie-Talkie, make phone calls, and send messages. Listen to Apple Music¹ and Apple Podcasts. And use Siri in all new ways. Apple Watch Series 3 lets you do it all right from your wrist.",
      category: "Smart Watch",
    },
    {
      id: "0002",
      image: "https://m.media-amazon.com/images/I/713BLl3u37L._AC_UY218_.jpg",
      name: "Apple Watch SE (GPS, 44mm) - Silver Aluminum Case with Abyss Blue Sport Band",
      slug: "apple Watch SE",
      price: "370",
      brand: "Apple",
      quantity: 20,
      rating: 4.0,
      numReviews: 12,
      description:
        "Apple Watch SE features the same accelerometer, gyroscope, and always-on altimeter as Apple Watch Series 6, and with the latest motion sensors and microphone, it offers robust health and safety capabilities including fall detection, Emergency SOS, international emergency calling, and the Noise app.",
      category: "Smart Watch",
    },
    {
      id: "0003",
      image: "https://m.media-amazon.com/images/I/71s-OXhQNDL._AC_UY218_.jpg",
      slug: "fitbit Versa 3",
      name: "Fitbit Versa 3 Health & Fitness Smartwatch with GPS, 24/7 Heart Rate, Alexa Built-in, 6+ Days Battery, Pink/Gold, One Size (S & L Bands Included)",
      price: "189.99",
      brand: "Fitbit",
      quantity: 28,
      rating: 4.0,
      numReviews: 12,
      description:
        "The main features of the Fitbit Versa 3 include built-in GPS, SpO2 monitoring, Active Zone Minutes activity tracking, two smart assistant options (Google Assistant feature is still being rolled out), heart rate variability tracking, over 20 exercise modes on board and SmartTrack.",
      category: "Smart Watch",
    },
    {
      id: "0004",
      image: "https://m.media-amazon.com/images/I/71I6s42MJYL._AC_UY218_.jpg",
      slug: "kOSPET Smart Watch for Men",
      name: "KOSPET Smart Watch for Men/Women Full Day Heart Rate Monitoring Blood Pressure/Sleep Monitoring/Women's Menstrual Cycle Reminder Android Smartwatch Magic 4 with 20 Sports Modes 5ATM Waterproof-Pink",
      price: "199",
      brand: "KOSPET",
      quantity: 14,
      rating: 4.0,
      numReviews: 12,
      description:
        " Rugged Smartwatch Wild Warrior Envisioned as a RUGGED smartwatch that built to withstand and work in tough environments. Being water-proof dust-proof, and shock-proof Adopts the tough sports style, the clear-cut edges make it durable and resistant to water and dust.",
      category: "Smart Watch",
    },
    {
      id: "0005",
      image: "https://m.media-amazon.com/images/I/71qNX0wixBL._AC_UY218_.jpg",
      name: "Fossil Gen 5 Carlyle Stainless Steel Touchscreen Smartwatch with Speaker, Heart Rate, GPS, Contactless Payments, and Smartphone Notifications",
      slug: "fossil Gen 5 Carlyle",
      price: "265",
      brand: "Fossil",
      quantity: 21,
      rating: 4.0,
      numReviews: 12,
      description:
        "Operating System: Wear OS by Google Sensors: Optical Heart Rate, Ambient Light, Barometric Altimeter, GPS, Accelerometer, Gyroscope, Microphone, Speaker Processor: Qualcomm Snapdragon Wear 3100 (our fastest yet) What’s in the Box: Smartwatch, USB Charging Cable, Quick Start Guide, Warranty Booklet.",
      category: "Smart Watch",
    },
    {
      id: "0006",
      image: "https://m.media-amazon.com/images/I/91Q6MEBj4mL._AC_UY218_.jpg",
      name: "Test Samsung Gear S Smartwatch, White 4GB (AT&T)",
      slug: "test Samsung Gear S",
      price: "414",
      brand: "Samsung",
      quantity: 5,
      rating: 4.0,
      numReviews: 12,
      description:
        "Tizen smartwatch with 1GHz Dual-Core median processor provides good performance when performing some functions of the Samsung Gear S (3G SM-R750). With one SIM card slot, the Samsung Gear S (3G SM-R750) allows download up to 21 Mbps for internet browsing, but it also depends on the carrier. Good connectivity of this device includes Bluetooth 4.1 + A2DP, WiFi 802.11 b/g/n (2.4Ghz), but it lacks NFC connection. Device with 67 grams including the battery. The Samsung Gear S (3G SM-R750) smartwatch is relatively thin with 12.5mm thickness.",
      category: "Smart Watch",
    },
    {
      id: "0007",
      image: "https://m.media-amazon.com/images/I/71EHBrHu6-S._AC_UY218_.jpg",
      name: "Garmin Hybrid Smartwatch with Real Watch Hands and Hidden Color Touchscreen Displays, rose gold with light sand case and band, 39mm, 010-02238-02",
      slug: "garmin Hybrid Smartwatch",
      price: "280",
      brand: "Garmin",
      quantity: 35,
      rating: 4.0,
      numReviews: 12,
      description:
        "Stylish Hybrid Smartwatch with Hidden Touchscreen Display and Real Watch Hands. Stay connected with smart features¹ such as music controls and smart notifications for incoming calls, text messages, calendar reminders and more24/7 heart rate² monitoring with Elevate™ wrist heart rate technology. Wellness monitoring tools, such as all-day stress tracking and a relaxation timer, help you manage stress; includes advanced sleep monitoring with REM sleepDisplays steps, calories, distance, heart rate, intensity minutes² and VO2 max. Effortlessly change your look with industry standard 20 mm quick release accessory bandsBattery life: up to 5 days in smart mode; up to 2 additional weeks in watch mode (hands tell time only).",
      category: "Smart Watch",
    },
    {
      id: "0008",
      image: "https://m.media-amazon.com/images/I/51f-Cfkk1hL._AC_UY218_.jpg",
      name: "Garmin Vivoactive 4S GPS Smartwatch with Music & Fitness Activity Tracker & Health Monitor Apps (Dust Rose/Gold) 010-02172-31 4 S Bundle with CPS Enhanced Protection Pack",
      slug: "garmin Vivoactive 4S GPS",
      price: "599",
      brand: "Garmin",
      quantity: 11,
      rating: 4.0,
      numReviews: 12,
      description:
        "This smartwatch is lightweight and has a robust body that is made of Stainless Steel. Moreover, the watch is extremely comfortable to wear and is waterproof since the weigh of the watch is around 40g.",
      category: "Smart Watch",
    },
    {
      id: "0009",
      image: "https://m.media-amazon.com/images/I/61FMoiYALPL._AC_UY218_.jpg",
      name: "Kids Smart Watch for Boys Girls - HD Touch Screen Sports Smartwatch Phone with Call Camera Games Recorder Alarm Music Player for Children Teen Students",
      slug: "goowjuer Kids Smartwatch",
      price: "241.99",
      brand: "Goowjuer",
      quantity: 15,
      rating: 3.0,
      numReviews: 29,
      description:
        " Kids can make and receive calls via the smartwatch. You can consult a local operator to purchase a SIM card that supports 2G signals. We give a SD card in the product ,not including SIM card.",
      category: "Smart Watch",
    },
  ],
};
export default products;
